version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=${MYSQLHOST}
      - PMA_PORT=${MYSQLPORT}
      - PMA_USER=${MYSQLUSER}
      - PMA_PASSWORD=${MYSQLPASSWORD}